---
  - name: Request to license device (BIG-IQ >= 7.1)
    uri:
      url: "https://{{ bigiq_provider.server }}:{{ bigiq_provider.port }}/mgmt/setup/license/activate"
      method: POST
      validate_certs: "{{ validate_certs }}"
      headers:
        X-F5-Auth-Token: "{{ f5_auth_token }}"
      body:
        baseRegKey: "{{ bigiq_license_key }}"
        addOnKeys: []
      body_format: json
    register: license_status

  - debug:
      msg: bigip license status is "{{ license_status }}"

  - name: Stop if licensing failed
    fail:
      msg: Failed to license the device
    when: license_status.json.status == 'LICENSING_FAILED'

  - name: Stop if license text was not generated
    fail:
      msg: Failed to generate license text
    when: >
      (license_status.json is defined and (license_status.json.status not in ['LICENSING_COMPLETE', 'NEED_EULA_ACCEPT'])) or
      (license_uela_status.json is defined and license_uela_status.json.status != 'LICENSING_COMPLETE')

  - name: Send EULA if requested (BIG-IQ >= 7.1)
    uri:
      url: "https://{{ bigiq_provider.server }}:{{ bigiq_provider.port }}/mgmt/setup/license/accept-eula"
      method: POST
      validate_certs: "{{ validate_certs }}"
      headers:
        X-F5-Auth-Token: "{{ f5_auth_token }}"
      body:
        baseRegKey: "{{ bigiq_license_key }}"
        dossier: "{{ license_status.json.dossier }}"
        eulaText: "{{ license_status.json.eulaText }}"
      body_format: json
    register: license_uela_status
    when: license_status.json.status == 'NEED_EULA_ACCEPT'

  - name: Stop if EULA sending failed
    fail:
      msg: Failed to license the device
    when: license_uela_status.json is defined and license_uela_status.json.status != 'LICENSING_COMPLETE'

  - name: Put license on device (BIG-IQ >= 7.1)
    uri:
      url: "https://{{ bigiq_provider.server }}:{{ bigiq_provider.port }}/mgmt/setup/license"
      method: POST
      validate_certs: "{{ validate_certs }}"
      headers:
        X-F5-Auth-Token: "{{ f5_auth_token }}"
      body:
        licenseText: "{{ license_status.json.licenseText }}"
      body_format: json
    when: license_uela_status.json is defined

  - name: Put license on device (BIG-IQ >= 7.1)
    uri:
      url: "https://{{ bigiq_provider.server }}:{{ bigiq_provider.port }}/mgmt/setup/license"
      method: POST
      validate_certs: "{{ validate_certs }}"
      headers:
        X-F5-Auth-Token: "{{ f5_auth_token }}"
      body:
        licenseText: "{{ license_status.json.licenseText }}"
      body_format: json
    when: license_uela_status.json is undefined and license_status.json is defined
